http:
  mode: debug # debug, test, release
  port: 1001
log:
  filename: /tmp/open.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: true
gpt:
  model : "gpt-3.5-turbo"
  apiKey: "Bearer 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"
  maxToken: 500